services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
    ports:
      - "5432:5432"
    volumes:
      - fraud_postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: [ "2181:2181" ]

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: [ zookeeper ]
    ports: [ "9092:9092" ]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # IMPORTANT FOR SINGLE NODE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  fraud-detector:
    build:
      context: ./services/fraud-detector
      dockerfile: Dockerfile
    image: fraud-detector:latest
    container_name: fraud-detector
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/frauddb
      SPRING_DATASOURCE_USERNAME: fraud
      SPRING_DATASOURCE_PASSWORD: fraud
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"

  ml-service:
    build:
      context: ./services
      dockerfile: ml-service/Dockerfile
    image: ml-service:latest
    container_name: ml-service
    depends_on:
      - postgres
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      KAFKA_COMPLETION_TOPIC: ML_Service_Response
    ports:
      - "8001:8001"

  image-service:
    build:
      context: ./services
      dockerfile: image-service/Dockerfile
    image: image-service:latest
    container_name: image-service
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql://fraud:fraud@postgres:5432/frauddb
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      KAFKA_COMPLETION_TOPIC: Image_Service_Response
    ports:
      - "8002:8002"

  consortium-service:
    build:
      context: ./services
      dockerfile: consortium-service/Dockerfile
    image: consortium-service:latest
    container_name: consortium-service
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql://fraud:fraud@postgres:5432/frauddb
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      KAFKA_COMPLETION_TOPIC: Consortium_Service_Response
    ports:
      - "8003:8003"

  rules-service:
    build:
      context: ./services/rules-service
      dockerfile: Dockerfile
    image: rules-service:latest
    container_name: rules-service
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/frauddb
      SPRING_DATASOURCE_USERNAME: fraud
      SPRING_DATASOURCE_PASSWORD: fraud
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8004:8004"

#
#  prometheus:
#    image: prom/prometheus:v2.53.0
#    ports: ["9090:9090"]
#    volumes:
#      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana:11.1.0
#    ports: ["3000:3000"]


volumes:
  fraud_postgres_data: