server:
  port: 8080
spring:
  application:
    name: fraud-detector
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/frauddb}
    username: ${SPRING_DATASOURCE_USERNAME:fraud}
    password: ${SPRING_DATASOURCE_PASSWORD:fraud}
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
fraud:
  Kafka:
    topics:
      consortium-service-response: Consortium_Service_Response
      image-service-response: Image_Service_Response
      rule-service-response: Rule_Service_Response
      ml-service-response: ML_Service_Response
    consumer-group: fraud-detector-completions