package com.research.fraud.statemachine;

public enum WorkflowState {
    RECEIVED,
    IMAGE_ANALYSIS_PENDING,
    CONSORTIUM_ANALYSIS_PENDING,
    WAITING_FOR_DEPENDENCIES,
    FEATURE_ENGINEERING,
    ML_ANALYSIS_PENDING,
    RULE_ANALYSIS_PENDING,
    FINALIZING,
    COMPLETED,
    FAILED
}
