server:
  port: 8084
spring:
  application:
    name: rules-service
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/frauddb
    username: fraud
    password: fraud
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
